package fr.formation.inti.entity;
// Generated 18 fEvr. 2022 E 08:19:10 by Hibernate Tools 3.6.0.Final

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ligues generated by hbm2java
 */

public class League implements java.io.Serializable {

	private Integer id;
	private String name;
	private String country;
	private String logo;
	private String season;
	
	
	
	public League() {
		super();
	}


	public League(Integer id, String name, String country, String logo) {
		super();
		this.id = id;
		this.name = name;
		this.country = country;
		this.logo = logo;
	}


	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getCountry() {
		return country;
	}


	public void setCountry(String country) {
		this.country = country;
	}


	public String getLogo() {
		return logo;
	}


	public void setLogo(String logo) {
		this.logo = logo;
	}


	@Override
	public String toString() {
		return "League [id=" + id + ", name=" + name + ", country=" + country + ", logo=" +logo + "]";
	}
	
	
	
	

}