package fr.formation.inti.entity;
// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Matchs generated by hbm2java
 */
@Entity
@Table(name = "matchs", catalog = "football")
public class Matchs implements java.io.Serializable {

	private Integer id;
	private Stades stades;
	
	
	private Equipes equipesByEquipesDomicilesIdEquipes;
	private Equipes equipesByEquipesExterieursIdEquipes;
	private String dates;
	private String scores;
	private String horaires;
	private Integer journee;

	public Matchs() {
	}

	public Matchs(Integer id, Stades stades, Equipes equipesByEquipesDomicilesIdEquipes, Equipes equipesByEquipesExterieursIdEquipes) {
        this.id = id;
        this.stades = stades;
        this.equipesByEquipesDomicilesIdEquipes = equipesByEquipesDomicilesIdEquipes;
        this.equipesByEquipesExterieursIdEquipes = equipesByEquipesExterieursIdEquipes;
    }

	public Matchs(Integer id, Stades stades, Equipes equipesByEquipesDomicilesIdEquipes, Equipes equipesByEquipesExterieursIdEquipes, String dates, String scores, String horaires, Integer journee) {
       this.id = id;
       this.stades = stades;
       this.equipesByEquipesDomicilesIdEquipes = equipesByEquipesDomicilesIdEquipes;
       this.equipesByEquipesExterieursIdEquipes = equipesByEquipesExterieursIdEquipes;
       this.dates = dates;
       this.scores = scores;
       this.horaires = horaires;
       this.journee = journee;
    }
   
//	@EmbeddedId

    
//    @AttributeOverrides( {
//        @AttributeOverride(name="idMatch", column=@Column(name="idMatch", nullable=false) ), 
//        @AttributeOverride(name="equipesByEquipesExterieursIdEquipes", column=@Column(name="équipes_extérieurs_idéquipes", nullable=false) ), 
//        @AttributeOverride(name="equipesByEquipesDomicilesIdEquipes", column=@Column(name="équipes_domiciles_idéquipes", nullable=false) ) } )
	@Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idMatch", nullable=false)
    public Integer getId() {
        return this.id;
    }

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stades_idstades", nullable = false)
	public Stades getStades() {
		return this.stades;
	}

	public void setStades(Stades stades) {
		this.stades = stades;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Équipes_domiciles_idÉquipes", nullable=false, insertable=false, updatable=false)
    public Equipes getEquipesByEquipesDomicilesIdEquipes() {
        return this.equipesByEquipesDomicilesIdEquipes;
    }

	public void setEquipesByEquipesDomicilesIdEquipes(Equipes equipesByEquipesDomicilesIdEquipes) {
        this.equipesByEquipesDomicilesIdEquipes = equipesByEquipesDomicilesIdEquipes;
    }

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Équipes_extérieurs_idÉquipes", nullable=false, insertable=false, updatable=false)
    public Equipes getEquipesByEquipesExterieursIdEquipes() {
        return this.equipesByEquipesExterieursIdEquipes;
    }

	public void setEquipesByEquipesExterieursIdEquipes(Equipes equipesByEquipesExterieursIdEquipes) {
        this.equipesByEquipesExterieursIdEquipes = equipesByEquipesExterieursIdEquipes;
    }

	@Column(name = "Dates", length = 45)
	public String getDates() {
		return this.dates;
	}

	public void setDates(String dates) {
		this.dates = dates;
	}

	@Column(name = "Scores", length = 45)
	public String getScores() {
		return this.scores;
	}

	public void setScores(String scores) {
		this.scores = scores;
	}

	@Column(name = "horaires", length = 45)
	public String getHoraires() {
		return this.horaires;
	}

	public void setHoraires(String horaires) {
		this.horaires = horaires;
	}

	@Column(name="journée")
    public Integer getJournee() {
        return this.journee;
    }

	public void setJournee(Integer journee) {
        this.journee = journee;
    }




}
