package fr.formation.inti.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

/**
 * Matchs generated by hbm2java
 */

public class Matchs2 implements java.io.Serializable {

	private Integer id;

	private String date;
	private String referee;
	@JsonIgnore
	private String score;
	
	

	public Matchs2() {
	}
	

	public Matchs2(Integer id, String date, String referee) {
		super();
		this.id = id;
		this.date = date;
		this.referee = referee;
		
	}

	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getReferee() {
		return referee;
	}

	public void setReferee(String referee) {
		this.referee = referee;
	}

	
	@Override
	public String toString() {
		return "Matchs2 [id=" + id + ", date=" + date + ", referee=" + referee+ "]";
	}


	public String getScore() {
		return score;
	}


	public void setScore(String score) {
		this.score = score;
	}
	
	
	
	

	

}