package fr.formation.inti.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

/**
 * Match generated by hbm2java
 */

public class Match implements java.io.Serializable {

	private Integer id;
	private Venue venue;
	private League league;
	private Team teamHome;
	private Team teamAway;
	
	private String date;
	private Integer scoreHome;
	private Integer scoreAway;
	private String status;

	
	public Match() {
		
	}
	
	
	
	
	public Match(Integer id, Venue venue, League league, Team teamHome, Team teamAway, String date, Integer scoreHome,
			Integer scoreAway, String status) {
		super();
		this.id = id;
		this.venue = venue;
		this.league = league;
		this.teamHome = teamHome;
		this.teamAway = teamAway;
		this.date = date;
		this.scoreHome = scoreHome;
		this.scoreAway = scoreAway;
		this.status=status;
	
	}




	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Venue getVenue() {
		return venue;
	}
	public void setVenue(Venue venue) {
		this.venue = venue;
	}
	public League getLeague() {
		return league;
	}
	public void setLeague(League league) {
		this.league = league;
	}
	public Team getTeamHome() {
		return teamHome;
	}
	public void setTeamHome(Team teamHome) {
		this.teamHome = teamHome;
	}
	public Team getTeamAway() {
		return teamAway;
	}
	public void setTeamAway(Team teamAway) {
		this.teamAway = teamAway;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	
	


	public Integer getScoreHome() {
		return scoreHome;
	}


	public void setScoreHome(Integer scoreHome) {
		this.scoreHome = scoreHome;
	}


	public Integer getScoreAway() {
		return scoreAway;
	}


	public void setScoreAway(Integer scoreAway) {
		this.scoreAway = scoreAway;
	}
	
	





	public String getStatus() {
		return status;
	}




	public void setStatus(String status) {
		this.status = status;
	}




	@Override
	public String toString() {
		return "Match [id=" + id + ", venue=" + venue + ", league=" + league + ", teamHome=" + teamHome + ", teamAway="
				+ teamAway + ", date=" + date + ", scoreHome=" + scoreHome + ", scoreAway=" + scoreAway +  "]";
	}
	
	
	
	
	


	
	

	

}