package fr.formation.inti.entity;
// Generated 18 fEvr. 2022 � 08:19:10 by Hibernate Tools 3.6.0.Final


import java.util.Arrays;

/**
 * �quipes generated by hbm2java
 */

public class Team  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String logo;
     private String code;
     private Venue stade;
     private String founded;
     private String country;
   

    public Team() {
    }
    
    


	public Team(Integer id, String name, String logo,String code,String founded,String country) {
		super();
		this.id = id;
		this.name = name;
		this.logo = logo;
		this.code = code;
		this.founded = founded;
		this.country = country;
	}




	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getLogo() {
		return logo;
	}


	public void setLogo(String logo) {
		this.logo = logo;
	}

	
	

	public Venue getStade() {
		return stade;
	}




	public void setStade(Venue stade) {
		this.stade = stade;
	}




	public String getCode() {
		return code;
	}




	public void setCode(String code) {
		this.code = code;
	}




	public String getFounded() {
		return founded;
	}




	public void setFounded(String founded) {
		this.founded = founded;
	}




	public String getCountry() {
		return country;
	}




	public void setCountry(String country) {
		this.country = country;
	}




	@Override
	public String toString() {
		return "Team [id=" + id + ", name=" + name + ", logo=" + logo + "]";
	}

	
    


}
