package fr.formation.inti.entity;
// Generated 18 fEvr. 2022 � 08:19:10 by Hibernate Tools 3.6.0.Final


import java.util.Arrays;

/**
 * �quipes generated by hbm2java
 */

public class Team  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String logo;
     

    public Team() {
    }
    
    


	public Team(Integer id, String name, String logo) {
		super();
		this.id = id;
		this.name = name;
		this.logo = logo;
	}




	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getLogo() {
		return logo;
	}


	public void setLogo(String logo) {
		this.logo = logo;
	}


	@Override
	public String toString() {
		return "Team [id=" + id + ", name=" + name + ", logo=" + logo + "]";
	}

	
    


}
