package fr.formation.inti.entity;
// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "football")
public class User implements java.io.Serializable {

	private int id_user;
	private Role role;
	
	private String password;
	
	private String email;
	
	
	private String prenom;
	
	
	private String nom;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date date;

	public User() {
	}

	public User(int id_user, Role role) {
		this.id_user = id_user;
		this.role = role;
	}

	public User(int id_user, Role role, String password, String email, String prenom, String nom, Date date) {
       this.id_user = id_user;
       this.role = role;
       this.password = password;
       this.email = email;
       this.prenom = prenom;
       this.nom = nom;
       this.date = date;
    }

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_user", unique = true, nullable = false)
	public int getIdUser() {
		return this.id_user;
	}

	public void setIdUser(int id_user) {
		this.id_user = id_user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_role", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name="prenom", length=45)
    public String getPrenom() {
        return this.prenom;
    }

	public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}